name: Test Emulator

on: 
  push:
  workflow_dispatch:
    inputs:
      api-level:
        description: 'API Level'
        required: true
        default: 23
        type: number  

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Android runner
        uses: "./.github/actions/android-emulator-runner"
        with:
          api-level: ${{inputs.api-level}}
